version: '3.8'

services:
  # Flask приложение
  flask-app:
    build: ./backend
    container_name: flask-api
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    volumes:
      - ./input_data:/app/input_data
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx как reverse proxy с SSL
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"  # Дополнительный порт для прямого доступа
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge