version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - LOG_FORMAT=${LOG_FORMAT}
      - MINIAPP_URL=${MINIAPP_URL}
    volumes:
      # Если нужно сохранять логи или данные
      - ./logs:/app/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge